# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-15 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieBase',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('doubanurl', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('director', models.CharField(max_length=30)),
                ('commenturl', models.CharField(max_length=150)),
            ],
        ),
    ]
