# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_commentbase'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentbase',
            table='commentbase',
        ),
    ]
