# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-21 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_moviecommentcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_word', models.CharField(max_length=50)),
                ('comment_word_count', models.IntegerField()),
                ('comment_movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.MovieBase')),
            ],
            options={
                'db_table': 'moviecommentword',
            },
        ),
    ]
