# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_emotion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emotion',
            new_name='MovieEmotion',
        ),
    ]
